# numpy
- 형이 전부 동일해야함.  
- 기본이 행렬임 [2차원]   -> 행렬.. 기억안나아아


> shape는 괄호가 없음 (python의 특징)  
> dtype는 괄호가 없음 (python의 특징)

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1] # <- 1차원 List
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기
# Type 가 다 똑같아야함.

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape # 5행 1열

(5,)

In [5]:
# 2차원 List 만들기
data2 = [
        [1,2,3,4],
        [5,6,7,8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2
# => 2행 4열
# DL 들어가면 중요!!

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape
# > (2, 4) 2행 4열이야 : 4차원 데이터

(2, 4)

In [8]:
# 0으로 구성된 1차원 배열을 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# 0으로 구성된 5행 2열
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# 0으로 구성된 3page의 5(row)행 2(column)열
# [[[0., 0.],[[[ <- 3차원이네
np.zeros([3, 5, 2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
# 1로만 구성된 배열생성(0,1만 명령어가 있음)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
# 10으로만 구성된 배열생성
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# 숫자 8로 구성된 3행 5열배열 생성
# [[ <- 2차원
np.full((3, 5), 8) # || np.full([3, 5], 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
# 범위가 있는 배열 생성 = > Python : arange (R : arrange)
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr3 = np.array([1,2,3,4,5],dtype=np.int64)
print(arr3.dtype)
print(arr3)

int64
[1 2 3 4 5]


In [19]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
print(float_arr1.dtype)
print(float_arr1)

float64
[1. 2. 3. 4. 5.]


In [20]:
# 행렬 연산
arr1 = np.array([
    [1,2,3],
    [4,5,6]
    ],dtype=np.float64
    )
arr1

# # 튜플로 쓸떈
# arr1 = np.array((
#     [1,2,3],
#     [4,5,6]
# ))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
    ],dtype=np.float64
    )
print(arr2)

[[ 7.  8.  9.]
 [10. 11. 12.]]


In [22]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 * 2)
print(np.sqrt(arr1))
arr3 = 1 / arr1
print(arr3)

[[ 8. 10. 12.]
 [14. 16. 18.]]
[[-6. -6. -6.]
 [-6. -6. -6.]]
[[ 7. 16. 27.]
 [40. 55. 72.]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [23]:
arr = np.arange(10)
print(arr)
print(arr[5])

#범위주기? 보기?
print(arr[5:9])

#값 바꾸기
arr[5:9] = 12
print(arr)

#범위값 보기
print(arr[:5])

print(arr[8:])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]
[ 0  1  2  3  4 12 12 12 12  9]
[0 1 2 3 4]
[12  9]


## 2차원 배열

In [24]:
arr2d = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
        ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
arr2d.dtype

dtype('int64')

In [26]:
# 2번 행의 자료 출력(자연어 처리할때 핸들링 잘해야함.)
arr2d[2,:]

array([ 9, 10, 11, 12])

In [27]:
# 1에서 2번행의 자료 출력 (index값이랑 똑같이 숫자를 셈)
print(arr2d[1:3,:],'\n')

# 3번 열의 자료 출력 (index값이랑 똑같이 숫자를 셈)
print(arr2d[:,3],'\n')

# 0, 1번 자료 출력 (index값이랑 똑같이 숫자를 셈)
print(arr2d[:,:2],'\n')

# 1행 2열의 자료 출력 (index값이랑 똑같이 숫자를 셈)
print(arr2d[1,2],'\n')


[[ 5  6  7  8]
 [ 9 10 11 12]] 

[ 4  8 12 16] 

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 

7 



In [28]:
# 값 바꾸기
print(arr2d,"\n\n")
arr2d[:2,1:3] = 0

print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 


[[ 1  0  0  4]
 [ 5  0  0  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---
# 난수 발생
- rand = 0부터 1사이의 균일 분포
- randn : 가우시안(?) 표준 정규 분포
- randint : 균일 분포의 정수 난수

## Boolean Indexing

In [29]:
names = np.array(["Charles","Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7, 4)

In [30]:
names
# dtype='<U7'??

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [31]:
names.shape #(7,) 7행

(7,)

In [32]:
data

array([[-0.70429654,  0.24172331, -0.65951658, -0.79677204],
       [-0.09314053,  0.53101225, -0.49601752, -0.02644874],
       [-0.36192935,  0.82200099,  0.30519536,  0.17741715],
       [ 1.19935868, -1.44061273, -0.70097953, -2.87937719],
       [-0.68792527,  0.31374828, -0.77930586, -0.52127187],
       [-0.79300579,  0.48627865,  0.43656031, -0.71916742],
       [-1.18289166, -1.06991579,  0.17949168, -0.2578093 ]])

In [33]:
data.shape #(7, 4) 7행 4열

(7, 4)

In [34]:
# Mask
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [35]:
data[names == "Charles", :] # True값에 해당하는 행을 출력한값. 이건게 Boolean Indexing

array([[-0.70429654,  0.24172331, -0.65951658, -0.79677204],
       [ 1.19935868, -1.44061273, -0.70097953, -2.87937719]])

In [36]:
data[(names =="Charles") | (names =="Kenny"), :]

array([[-0.70429654,  0.24172331, -0.65951658, -0.79677204],
       [-0.09314053,  0.53101225, -0.49601752, -0.02644874],
       [ 1.19935868, -1.44061273, -0.70097953, -2.87937719],
       [-0.79300579,  0.48627865,  0.43656031, -0.71916742],
       [-1.18289166, -1.06991579,  0.17949168, -0.2578093 ]])

In [37]:
data[:] #all

array([[-0.70429654,  0.24172331, -0.65951658, -0.79677204],
       [-0.09314053,  0.53101225, -0.49601752, -0.02644874],
       [-0.36192935,  0.82200099,  0.30519536,  0.17741715],
       [ 1.19935868, -1.44061273, -0.70097953, -2.87937719],
       [-0.68792527,  0.31374828, -0.77930586, -0.52127187],
       [-0.79300579,  0.48627865,  0.43656031, -0.71916742],
       [-1.18289166, -1.06991579,  0.17949168, -0.2578093 ]])

In [38]:
# 4번째 열을 가져오는것
data[:,3]

array([-0.79677204, -0.02644874,  0.17741715, -2.87937719, -0.52127187,
       -0.71916742, -0.2578093 ])

In [39]:
# data의 4번째 열 값중 0보다 작은 것의 mask 만들기
data[:,3] < 0

array([ True,  True, False,  True,  True,  True,  True])

In [40]:
data[data[:,3] < 0, :]

array([[-0.70429654,  0.24172331, -0.65951658, -0.79677204],
       [-0.09314053,  0.53101225, -0.49601752, -0.02644874],
       [ 1.19935868, -1.44061273, -0.70097953, -2.87937719],
       [-0.68792527,  0.31374828, -0.77930586, -0.52127187],
       [-0.79300579,  0.48627865,  0.43656031, -0.71916742],
       [-1.18289166, -1.06991579,  0.17949168, -0.2578093 ]])

In [41]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
# true 인애들은 알아서 0으로 바뀜... 왜?
data[data[:,3] < 0 , :] = 0
data
 

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.36192935,  0.82200099,  0.30519536,  0.17741715],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [42]:
# 정렬
arr = np.random.rand(8)
arr

array([0.31396126, 0.13430488, 0.11568271, 0.22673642, 0.03349386,
       0.23923268, 0.90943981, 0.33822807])

In [43]:
# 오름차순 정렬
np.sort(arr)

array([0.03349386, 0.11568271, 0.13430488, 0.22673642, 0.23923268,
       0.31396126, 0.33822807, 0.90943981])

In [44]:
# 내림차순 정렬
# 1차원 정렬인 데이터 하나짜리라 키워드로 사용
np.sort(arr)[::-1]

array([0.90943981, 0.33822807, 0.31396126, 0.23923268, 0.22673642,
       0.13430488, 0.11568271, 0.03349386])

In [45]:
arr = np.random.rand(5, 3)
arr

array([[0.35300389, 0.73586198, 0.8993184 ],
       [0.49947402, 0.05808638, 0.79861685],
       [0.39921158, 0.71866093, 0.58262504],
       [0.0201676 , 0.03494496, 0.56147565],
       [0.3180883 , 0.00674899, 0.53474542]])

In [46]:
# 오름차순
np.sort(arr, axis=0) # 0 : 열방향

array([[0.0201676 , 0.00674899, 0.53474542],
       [0.3180883 , 0.03494496, 0.56147565],
       [0.35300389, 0.05808638, 0.58262504],
       [0.39921158, 0.71866093, 0.79861685],
       [0.49947402, 0.73586198, 0.8993184 ]])

In [47]:
# 오름차순
np.sort(arr, axis=1) # 1 : 행방향

array([[0.35300389, 0.73586198, 0.8993184 ],
       [0.05808638, 0.49947402, 0.79861685],
       [0.39921158, 0.58262504, 0.71866093],
       [0.0201676 , 0.03494496, 0.56147565],
       [0.00674899, 0.3180883 , 0.53474542]])

In [48]:
# 내림차순
np.sort(arr, axis=0)[::-1] # 0 : 열방향

array([[0.49947402, 0.73586198, 0.8993184 ],
       [0.39921158, 0.71866093, 0.79861685],
       [0.35300389, 0.05808638, 0.58262504],
       [0.3180883 , 0.03494496, 0.56147565],
       [0.0201676 , 0.00674899, 0.53474542]])

In [49]:
# 내림차순
np.sort(arr, axis=0)[:,::-1] # 1 : 행방향

array([[0.53474542, 0.00674899, 0.0201676 ],
       [0.56147565, 0.03494496, 0.3180883 ],
       [0.58262504, 0.05808638, 0.35300389],
       [0.79861685, 0.71866093, 0.39921158],
       [0.8993184 , 0.73586198, 0.49947402]])

In [50]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# *****reshape(중요!)
- 데이터의 차원을 바꿀때 사용

In [51]:
arr = np.arange(1, 9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
arr.shape # 8개의 행이 있다

(8,)

In [53]:
# *** 2차원 배열로 변경(이런거 잘 해야함)
# 1차원 배열을 2차원 배열로 바꿨네~!
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
# 3채원 배열로 변경
# 이미지 프로세싱, 보이스 프로세싱 전부 3차원으로 사용 많이 함!
arr2 = np.reshape(arr,(2,2,2)) # (page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 거꾸로하는거 중요!(-1 사용법)
- 한줄로 데이터가 쫙 있어야 받아서 공부를 할수 있음

In [55]:
# 2차원 배열을 1차원으로 변경(DL 에서는 차원수는 반드시 표시해줘야함 :( ,차원))
# 열은 하나인데 행은 모르겠어(-1)
# -1 : 데이터 갯수를 모를때 (행의 수는 알아서 지정해라)
arr3 = arr1.reshape(-1, 1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [56]:
arr4 = arr2.reshape(-1, 1)
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [57]:
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
# 대각선으로 정답값. 틀린게 아님.(단위행렬)
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

##### 단위 행렬
|1 0 0|  
|0 1 0|  
|0 0 1|  