In [1]:
# GPU 사용 설정
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = '1'

In [2]:
import pandas as pd
data= pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

- admit : 1합격,0불합격
- gre : 영어 성적
- gpa : 학점
- rank : 지원한 대학원 수준

### Preprocessing(전처리)

In [3]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [4]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른값으로 대체
# data.fillna(100)

In [5]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [7]:
# 영어 점수의 최소값과 최대값
print("최대값 :",data['gre'].max())
print("최소값 :",data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 425 entries, 0 to 425
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   admit   425 non-null    int64  
 1   gre     425 non-null    float64
 2   gpa     425 non-null    float64
 3   rank    425 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 16.6 KB


In [9]:
# Training Data
x = data[['gre', 'gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [10]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [11]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 입력층 3개. 출력은 1개

---
## Deep Learning Model 만들기

In [12]:
from tensorflow import keras

In [13]:
# 입력레이어를 주는데 층은 아니다?
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation='tanh')
output_layer = keras.layers.Dense(1, activation='sigmoid')

In [14]:
model = keras.Sequential(
    [input_layer,
    hidden_layer,
    output_layer]
)

Optimizer => Learning rate를 알맞게 조정해줌 ->(y - y^)
- adam
- adagrad
- adadelta
- rmsprop
- sgd  

loss : 손실함수
- binary_crossentropy : 분류 및 확률 예측 함수

metrics : 모델의 평가 기준


In [15]:
# 손실함수
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [20]:
# 학습 시키기
# 일반적인 fit은 못씀 pandas에 들어있어서 -> numpy로 바꿔줘야해
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
14/14 [==============================] - 0s 526us/step - loss: 0.6792 - accuracy: 0.5412
Epoch 2/500
14/14 [==============================] - 0s 542us/step - loss: 0.6633 - accuracy: 0.6235
Epoch 3/500
14/14 [==============================] - 0s 494us/step - loss: 0.6494 - accuracy: 0.6212
Epoch 4/500
14/14 [==============================] - 0s 483us/step - loss: 0.6407 - accuracy: 0.6400
Epoch 5/500
14/14 [==============================] - 0s 477us/step - loss: 0.6758 - accuracy: 0.5153
Epoch 6/500
14/14 [==============================] - 0s 568us/step - loss: 0.6508 - accuracy: 0.6071
Epoch 7/500
14/14 [==============================] - 0s 504us/step - loss: 0.6481 - accuracy: 0.6376
Epoch 8/500
14/14 [==============================] - 0s 479us/step - loss: 0.6472 - accuracy: 0.6424
Epoch 9/500
14/14 [==============================] - 0s 503us/step - loss: 0.6519 - accuracy: 0.5976
Epoch 10/500
14/14 [==============================] - 0s 510us/step - loss: 0.6373 - accura

In [21]:
# hidden layer 가중치 값 출력
# 히든레이어에 AF를 주지 않으면 이값이 그대로 넘어감
hidden_layer.get_weights()[0]

array([[-1.52824175e+00,  1.51972032e+00, -1.65867507e-02,
         1.42348862e+00, -1.74821410e-02, -1.45454854e-02,
        -1.81747004e-02, -1.66664906e-02,  1.33711696e+00,
        -2.15973649e-02,  1.58062255e+00, -1.12097204e+00,
         1.48314106e+00, -1.50740874e+00,  1.52807891e+00,
        -2.00549234e-02,  1.10130513e+00, -9.91378631e-03,
        -2.13162918e-02, -1.79486182e-02, -2.00353302e-02,
        -1.66915450e-02,  1.51048100e+00,  1.71954483e-02,
         1.54322255e+00, -1.57212520e+00, -1.48679173e+00,
        -1.65868402e-02,  1.56837869e+00,  1.86125338e-02,
        -1.60491504e-02, -2.31818273e-03, -1.85612645e-02,
         1.46263409e+00,  1.42183340e+00,  1.74425058e-02,
        -1.33077216e+00, -1.68216676e-02, -1.94556788e-02,
        -1.34820426e-02, -1.11406255e+00,  1.51750734e-02,
        -1.48323083e+00, -1.57606956e-02,  1.52904642e+00,
        -3.54641676e-03,  1.77504588e-02, -1.82617232e-02,
         1.69706177e-02,  2.04862356e-02,  1.79297198e-0

In [22]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [23]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[-0.99999976,  0.99999976, -0.9999997 , ...,  0.9999997 ,
         0.9999996 , -0.99999976],
       [-0.99999976,  0.99999976, -0.99999976, ...,  0.99999976,
         0.99999976, -0.99999976],
       [-0.99999976,  0.99999976, -0.99999976, ...,  0.99999976,
         0.99999976, -0.99999976],
       ...,
       [-0.99999976,  0.99999976, -0.99999976, ...,  0.99999976,
         0.99999976, -0.99999976],
       [-0.99999976,  0.99999976, -0.99999976, ...,  0.99999976,
         0.99999976, -0.99999976],
       [-0.99999976,  0.99999976, -0.99999976, ...,  0.99999976,
         0.99999976, -0.99999976]], dtype=float32)>